name: bacon
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.21.2
  - python=3.8.12
  - pytorch=1.10.1
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - torchvision=0.11.2
  - pip
  - pip:
    - argparse==1.4.0
    - configargparse==1.5.3
    - gdown==4.2.0
    - matplotlib==3.4.3
    - pymcubes==0.1.2
    - scikit-image==0.18.3
    - scipy==1.7.1
    - tqdm==4.62.3
    - trimesh==3.9.35
